"""
05_merge_and_validate_gold.py

Merge Table 1 (Summary) and Table 2 (Comprehensive) from the official
SEBI BRSR -> GRI linkage document into a single gold dataset.

IMPORTANT DESIGN CHANGE
-----------------------
The earlier version trusted `gri_codes_json` generated by scripts 03/04.
That caused a catastrophic failure when the intermediate JSON was empty
even though `gri_text_raw` contained valid GRI citations.

This version therefore uses a robust two-level strategy:

    1. Try structured `gri_codes_json`.
    2. If it is empty/broken, extract GRI disclosure codes directly from
       the authoritative `gri_text_raw`.

Thus:

    raw official GRI text
            |
            +---- structured JSON, if valid
            |
            +---- raw-text fallback
            |
            v
       normalized GRI code set
            |
            v
       Table 1 <-> Table 2 comparison

The output preserves:
    - Table 1 raw GRI text
    - Table 2 raw GRI text
    - extracted codes from each
    - shared / union / consensus codes
    - agreement status
    - mapping semantics
    - QA flags

Outputs
-------
data/processed/gold_pairs.csv
data/processed/qa_flags.csv
"""


import csv
import json
import pathlib
import sys
from collections import Counter


# ---------------------------------------------------------------------
# Project imports
# ---------------------------------------------------------------------

BASE = pathlib.Path(__file__).resolve().parents[1]
sys.path.insert(0, str(BASE))

from src.gri_patterns import extract_disclosure_codes


# ---------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------

T1_PATH = BASE / "data" / "interim" / "table1_summary.csv"
T2_PATH = BASE / "data" / "interim" / "table2_comprehensive.csv"

OUT_GOLD = BASE / "data" / "processed" / "gold_pairs.csv"
OUT_QA = BASE / "data" / "processed" / "qa_flags.csv"


# ---------------------------------------------------------------------
# CSV helpers
# ---------------------------------------------------------------------

def load_csv(path):
    """Load a CSV file as a list of dictionaries."""
    if not path.exists():
        raise FileNotFoundError(f"Required input file not found: {path}")

    with open(path, newline="", encoding="utf-8") as f:
        return list(csv.DictReader(f))


# ---------------------------------------------------------------------
# GRI code extraction
# ---------------------------------------------------------------------

def normalize_code(code):
    """
    Normalize a GRI disclosure code.

    Examples
    --------
    405-1-a-I   -> 405-1-A-I
    403-10-b-ii -> 403-10-B-II
    """
    if not code:
        return ""

    parts = str(code).strip().split("-")

    if len(parts) < 2:
        return str(code).strip().upper()

    normalized = [parts[0], parts[1]]

    for part in parts[2:]:
        normalized.append(part.upper())

    return "-".join(normalized)


def parse_structured_codes(codes_json):
    """
    Parse the structured gri_codes_json generated by scripts 03/04.

    Supports:

        [
            {
                "standard": "403",
                "standard_name": "...",
                "year": "2018",
                "disclosures": [
                    "403-1-A",
                    "403-1-B"
                ]
            }
        ]

    Also tolerates a flat list of strings.

    Returns
    -------
    set[str]
    """
    if not codes_json:
        return set()

    # Some old files contain NaN-like strings.
    if str(codes_json).strip().lower() in {
        "",
        "nan",
        "none",
        "null",
    }:
        return set()

    try:
        parsed = json.loads(codes_json)
    except (json.JSONDecodeError, TypeError, ValueError):
        return set()

    if not isinstance(parsed, list):
        return set()

    codes = set()

    for entry in parsed:

        # Expected structured format
        if isinstance(entry, dict):

            disclosures = entry.get("disclosures", [])

            if isinstance(disclosures, list):
                for disclosure in disclosures:
                    if disclosure:
                        normalized = normalize_code(disclosure)
                        if normalized:
                            codes.add(normalized)

        # Also support a simple list:
        # ["403-1-A", "403-1-B"]
        elif isinstance(entry, str):
            normalized = normalize_code(entry)

            if normalized:
                codes.add(normalized)

    return codes


def extract_codes_robust(codes_json="", raw_text=""):
    """
    Robustly extract GRI codes.

    Priority:

        structured JSON
            |
            | if empty/broken
            v
        raw GRI text extraction

    This is the critical fix for the current pipeline.
    """

    # -------------------------------------------------------------
    # 1. Try structured extraction first.
    # -------------------------------------------------------------

    structured = parse_structured_codes(codes_json)

    if structured:
        return structured, "structured_json"

    # -------------------------------------------------------------
    # 2. FALLBACK: extract directly from raw GRI text.
    # -------------------------------------------------------------

    if raw_text:
        try:
            raw_codes = extract_disclosure_codes(raw_text)

            normalized = {
                normalize_code(code)
                for code in raw_codes
                if code
            }

            if normalized:
                return normalized, "raw_text_fallback"

        except Exception:
            # Never allow a parsing problem to kill the entire merge.
            pass

    # -------------------------------------------------------------
    # 3. Nothing found.
    # -------------------------------------------------------------

    return set(), "none"


# ---------------------------------------------------------------------
# Code serialization
# ---------------------------------------------------------------------

def codes_to_json(codes):
    """Serialize a code set deterministically."""
    return json.dumps(
        sorted(codes),
        ensure_ascii=False,
    )


# ---------------------------------------------------------------------
# Mapping semantics
# ---------------------------------------------------------------------

def infer_mapping_semantics(match_type, remarks=""):
    """
    Preserve the existing match_type semantics while adding a useful
    normalized mapping_semantics field.

    Table 1's match_type remains authoritative.

    Table 2 remarks can contain information such as:
        (1a)
        (2a)
        (2b)

    We do NOT infer a new semantic class from those annotations here
    unless the official match_type already tells us that the mapping
    is partial.

    This avoids inventing labels that are not explicitly supported.
    """

    match_type = (match_type or "").strip().lower()
    remarks = (remarks or "").strip()

    if match_type == "direct":
        return "direct"

    if match_type == "can_be_covered_by":
        return "partial"

    if match_type == "no_direct_linkage":
        return "no_direct_linkage"

    return "unspecified"


# ---------------------------------------------------------------------
# Agreement classification
# ---------------------------------------------------------------------

def classify_code_agreement(codes_t1, codes_t2):
    """
    Compare normalized GRI code sets.

    Returns one of:

        exact
        partial_overlap
        disagreement
        table1_only
        table2_only
        no_gri_code
    """

    if not codes_t1 and not codes_t2:
        return "no_gri_code"

    if codes_t1 and not codes_t2:
        return "table1_only"

    if codes_t2 and not codes_t1:
        return "table2_only"

    if codes_t1 == codes_t2:
        return "exact"

    shared = codes_t1 & codes_t2

    if shared:
        return "partial_overlap"

    return "disagreement"


# ---------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------

def main():

    print("=" * 70)
    print("05_merge_and_validate_gold")
    print("=" * 70)

    # -------------------------------------------------------------
    # Load
    # -------------------------------------------------------------

    t1_rows = load_csv(T1_PATH)
    t2_rows = load_csv(T2_PATH)

    print(f"Loaded Table 1 rows: {len(t1_rows)}")
    print(f"Loaded Table 2 rows: {len(t2_rows)}")

    # -------------------------------------------------------------
    # Index by BRSR ID
    # -------------------------------------------------------------

    t1_by_id = {}

    for row in t1_rows:
        brsr_id = row.get("brsr_id", "").strip()

        if brsr_id:
            t1_by_id.setdefault(brsr_id, []).append(row)

    t2_by_id = {}

    for row in t2_rows:
        brsr_id = row.get("brsr_id", "").strip()

        if brsr_id:
            t2_by_id.setdefault(brsr_id, []).append(row)

    all_ids = sorted(
        set(t1_by_id) | set(t2_by_id)
    )

    # -------------------------------------------------------------
    # Output containers
    # -------------------------------------------------------------

    gold_records = []
    qa_flags = []

    # Diagnostics
    extraction_sources_t1 = Counter()
    extraction_sources_t2 = Counter()

    # -------------------------------------------------------------
    # Process each BRSR ID
    # -------------------------------------------------------------

    for brsr_id in all_ids:

        t1_list = t1_by_id.get(brsr_id, [])
        t2_list = t2_by_id.get(brsr_id, [])

        # ---------------------------------------------------------
        # Duplicate detection
        # ---------------------------------------------------------

        if len(t1_list) > 1:
            qa_flags.append({
                "brsr_id": brsr_id,
                "reason": (
                    f"Table 1 contains {len(t1_list)} rows for this ID. "
                    "Possible unresolved multi-part indicator."
                ),
            })

        if len(t2_list) > 1:
            qa_flags.append({
                "brsr_id": brsr_id,
                "reason": (
                    f"Table 2 contains {len(t2_list)} rows for this ID. "
                    "Possible unresolved multi-part indicator."
                ),
            })

        # For now use first occurrence but retain QA flag above.
        t1 = t1_list[0] if t1_list else None
        t2 = t2_list[0] if t2_list else None

        # ---------------------------------------------------------
        # Table coverage
        # ---------------------------------------------------------

        if t1 is None:
            qa_flags.append({
                "brsr_id": brsr_id,
                "reason": (
                    "present in Table 2 only; missing from Table 1"
                ),
            })

        if t2 is None:
            qa_flags.append({
                "brsr_id": brsr_id,
                "reason": (
                    "present in Table 1 only; missing from Table 2"
                ),
            })

        # ---------------------------------------------------------
        # Raw GRI text
        # ---------------------------------------------------------

        gri_text_t1 = (
            t1.get("gri_text_raw", "").strip()
            if t1
            else ""
        )

        gri_text_t2 = (
            t2.get("gri_text_raw", "").strip()
            if t2
            else ""
        )

        # ---------------------------------------------------------
        # Robust GRI extraction
        # ---------------------------------------------------------

        if t1:

            codes_t1, source_t1 = extract_codes_robust(
                codes_json=t1.get("gri_codes_json", ""),
                raw_text=gri_text_t1,
            )

            extraction_sources_t1[source_t1] += 1

        else:

            codes_t1 = set()
            extraction_sources_t1["none"] += 1

        if t2:

            codes_t2, source_t2 = extract_codes_robust(
                codes_json=t2.get("gri_codes_json", ""),
                raw_text=gri_text_t2,
            )

            extraction_sources_t2[source_t2] += 1

        else:

            codes_t2 = set()
            extraction_sources_t2["none"] += 1

        # ---------------------------------------------------------
        # Code comparison
        # ---------------------------------------------------------

        shared_codes = codes_t1 & codes_t2
        union_codes = codes_t1 | codes_t2

        agreement = classify_code_agreement(
            codes_t1,
            codes_t2,
        )

        # ---------------------------------------------------------
        # QA around code disagreement
        # ---------------------------------------------------------

        if agreement == "disagreement":

            qa_flags.append({
                "brsr_id": brsr_id,
                "reason": (
                    "Table 1 and Table 2 contain non-overlapping GRI "
                    f"codes. Table1={sorted(codes_t1)}; "
                    f"Table2={sorted(codes_t2)}"
                ),
            })

        elif agreement == "partial_overlap":

            qa_flags.append({
                "brsr_id": brsr_id,
                "reason": (
                    "Table 1 and Table 2 have partially overlapping "
                    f"GRI codes. Shared={sorted(shared_codes)}; "
                    f"Table1-only={sorted(codes_t1 - codes_t2)}; "
                    f"Table2-only={sorted(codes_t2 - codes_t1)}"
                ),
            })

        elif agreement == "table1_only":

            # This does NOT necessarily mean Table 2 is wrong.
            # It may be a parser issue or a difference in how the
            # tables express the same relationship.
            qa_flags.append({
                "brsr_id": brsr_id,
                "reason": (
                    "GRI code found in Table 1 but not Table 2. "
                    f"Table1={sorted(codes_t1)}. "
                    "Inspect Table 2 raw text before treating this "
                    "as a genuine disagreement."
                ),
            })

        elif agreement == "table2_only":

            qa_flags.append({
                "brsr_id": brsr_id,
                "reason": (
                    "GRI code found in Table 2 but not Table 1. "
                    f"Table2={sorted(codes_t2)}. "
                    "Inspect Table 1 raw text before treating this "
                    "as a genuine disagreement."
                ),
            })

        # ---------------------------------------------------------
        # Match type
        # ---------------------------------------------------------

        if t1:
            match_type = t1.get(
                "match_type",
                "unspecified",
            )
        elif t2:
            match_type = t2.get(
                "match_type",
                "unspecified",
            )
        else:
            match_type = "unspecified"

        # Table 1 is authoritative when available.
        if t1 and t2:

            t1_match = t1.get("match_type", "")
            t2_match = t2.get("match_type", "")

            if t1_match != t2_match:

                qa_flags.append({
                    "brsr_id": brsr_id,
                    "reason": (
                        "Match type disagreement. "
                        f"Table1={t1_match}; "
                        f"Table2={t2_match}. "
                        "Table 1 retained as authoritative."
                    ),
                })

        # ---------------------------------------------------------
        # Mapping semantics
        # ---------------------------------------------------------

        remarks = (
            t2.get("remarks", "").strip()
            if t2
            else ""
        )

        mapping_semantics = infer_mapping_semantics(
            match_type,
            remarks,
        )

        # ---------------------------------------------------------
        # Metadata
        # ---------------------------------------------------------

        section = (
            t2.get("section", "")
            if t2
            else ""
        )

        principle = (
            t2.get("principle", "")
            if t2
            else ""
        )

        indicator_type = (
            t2.get("indicator_type", "")
            if t2
            else ""
        )

        brsr_text = (
            t2.get("brsr_text", "")
            if t2
            else ""
        )

        # ---------------------------------------------------------
        # Construct gold record
        # ---------------------------------------------------------

        gold_records.append({

            "brsr_id": brsr_id,

            "section": section,

            "principle": principle,

            "indicator_type": indicator_type,

            "brsr_text": brsr_text,

            "match_type": match_type,

            "mapping_semantics": mapping_semantics,

            # Table-specific normalized codes
            "gri_codes_table1": codes_to_json(codes_t1),

            "gri_codes_table2": codes_to_json(codes_t2),

            # Intersection
            "gri_codes_shared": codes_to_json(shared_codes),

            # Union
            "gri_codes_union": codes_to_json(union_codes),

            # Consensus:
            # exact agreement -> same set
            # partial overlap -> shared subset
            # disagreement -> empty
            # one-sided -> whichever table has evidence
            #
            # This is intentionally conservative.
            "gri_codes_consensus": codes_to_json(
                (
                    codes_t1
                    if agreement == "exact"
                    else shared_codes
                    if agreement == "partial_overlap"
                    else codes_t1
                    if agreement == "table1_only"
                    else codes_t2
                    if agreement == "table2_only"
                    else set()
                )
            ),

            "gri_code_agreement": agreement,

            # Preserve raw official text.
            "gri_text_table1": gri_text_t1,

            "gri_text_table2": gri_text_t2,

            "remarks": remarks,

            "in_table1": bool(t1),

            "in_table2": bool(t2),
        })

    # -----------------------------------------------------------------
    # Write gold dataset
    # -----------------------------------------------------------------

    OUT_GOLD.parent.mkdir(
        parents=True,
        exist_ok=True,
    )

    gold_fields = [
        "brsr_id",
        "section",
        "principle",
        "indicator_type",
        "brsr_text",
        "match_type",
        "mapping_semantics",
        "gri_codes_table1",
        "gri_codes_table2",
        "gri_codes_shared",
        "gri_codes_union",
        "gri_codes_consensus",
        "gri_code_agreement",
        "gri_text_table1",
        "gri_text_table2",
        "remarks",
        "in_table1",
        "in_table2",
    ]

    with open(
        OUT_GOLD,
        "w",
        newline="",
        encoding="utf-8",
    ) as f:

        writer = csv.DictWriter(
            f,
            fieldnames=gold_fields,
        )

        writer.writeheader()
        writer.writerows(gold_records)

    # -----------------------------------------------------------------
    # Write QA flags
    # -----------------------------------------------------------------

    OUT_QA.parent.mkdir(
        parents=True,
        exist_ok=True,
    )

    with open(
        OUT_QA,
        "w",
        newline="",
        encoding="utf-8",
    ) as f:

        writer = csv.DictWriter(
            f,
            fieldnames=[
                "brsr_id",
                "reason",
            ],
        )

        writer.writeheader()
        writer.writerows(qa_flags)

    # -----------------------------------------------------------------
    # Statistics
    # -----------------------------------------------------------------

    match_counts = Counter(
        r["match_type"]
        for r in gold_records
    )

    agreement_counts = Counter(
        r["gri_code_agreement"]
        for r in gold_records
    )

    mapping_counts = Counter(
        r["mapping_semantics"]
        for r in gold_records
    )

    both_count = sum(
        1
        for r in gold_records
        if r["in_table1"] and r["in_table2"]
    )

    only_t1 = sum(
        1
        for r in gold_records
        if r["in_table1"] and not r["in_table2"]
    )

    only_t2 = sum(
        1
        for r in gold_records
        if r["in_table2"] and not r["in_table1"]
    )

    t1_with_codes = sum(
        1
        for r in gold_records
        if json.loads(r["gri_codes_table1"])
    )

    t2_with_codes = sum(
        1
        for r in gold_records
        if json.loads(r["gri_codes_table2"])
    )

    # -----------------------------------------------------------------
    # Print report
    # -----------------------------------------------------------------

    print()
    print("=" * 60)
    print("GOLD DATASET")
    print("=" * 60)

    print(f"Gold records: {len(gold_records)}")
    print(f"Table 1 rows: {len(t1_rows)}")
    print(f"Table 2 rows: {len(t2_rows)}")

    print()
    print("TABLE COVERAGE")
    print(f"  Present in both:      {both_count}")
    print(f"  Table 1 only:         {only_t1}")
    print(f"  Table 2 only:         {only_t2}")

    print()
    print("GRI CODE EXTRACTION")
    print(
        f"  Records with GRI codes in Table 1: "
        f"{t1_with_codes}"
    )
    print(
        f"  Records with GRI codes in Table 2: "
        f"{t2_with_codes}"
    )

    print()
    print("EXTRACTION SOURCE — TABLE 1")
    for source, count in extraction_sources_t1.items():
        print(f"  {source:20s}: {count}")

    print()
    print("EXTRACTION SOURCE — TABLE 2")
    for source, count in extraction_sources_t2.items():
        print(f"  {source:20s}: {count}")

    print()
    print("GRI CODE AGREEMENT")

    for category in [
        "exact",
        "partial_overlap",
        "disagreement",
        "table1_only",
        "table2_only",
        "no_gri_code",
    ]:
        print(
            f"  {category:17s}: "
            f"{agreement_counts.get(category, 0)}"
        )

    print()
    print("MATCH TYPE")

    for key, value in sorted(match_counts.items()):
        print(
            f"  {key:22s}: {value}"
        )

    print()
    print("MAPPING SEMANTICS")

    for key, value in sorted(mapping_counts.items()):
        print(
            f"  {key:22s}: {value}"
        )

    print()
    print(f"QA flags: {len(qa_flags)}")

    print()
    print(f"Gold output -> {OUT_GOLD}")
    print(f"QA output   -> {OUT_QA}")

    print()
    print("=" * 60)
    print("ANCHOR CHECKS")
    print("=" * 60)

    anchor_ids = [
        "A19",
        "P3-E10a",
        "P3-E10b",
        "P3-E10c",
        "P3-E10d",
        "P6-E1",
        "P6-E8",
        "P6-E9",
    ]

    by_id = {
        r["brsr_id"]: r
        for r in gold_records
    }

    for brsr_id in anchor_ids:

        row = by_id.get(brsr_id)

        print()
        print(f"ID: {brsr_id}")

        if not row:
            print("  NOT FOUND")
            continue

        print(
            "  Table1 codes:",
            row["gri_codes_table1"],
        )

        print(
            "  Table2 codes:",
            row["gri_codes_table2"],
        )

        print(
            "  Shared:",
            row["gri_codes_shared"],
        )

        print(
            "  Union:",
            row["gri_codes_union"],
        )

        print(
            "  Agreement:",
            row["gri_code_agreement"],
        )

        print(
            "  Match type:",
            row["match_type"],
        )

    print()
    print("=" * 60)
    print("DONE")
    print("=" * 60)


if __name__ == "__main__":
    main()